import { Medicine, StateInfo } from '../types';

export const SEED_DEFAULT = 2026;

export const STATES: StateInfo[] = [
  {
    id: 'tn',
    name: 'Tamil Nadu',
    code: 'TN',
    historyDays: 90,
    regionType: 'Coastal & Industrial',
    phcCount: 25,
  },
  {
    id: 'up',
    name: 'Uttar Pradesh',
    code: 'UP',
    historyDays: 90,
    regionType: 'Dense Plains & Riverine',
    phcCount: 26,
  },
  {
    id: 'as',
    name: 'Assam',
    code: 'AS',
    historyDays: 45, // Data-constrained state to demonstrate federated learning benefit
    regionType: 'Flood-Prone & Remote Hilly',
    phcCount: 24,
  },
  {
    id: 'rj',
    name: 'Rajasthan',
    code: 'RJ',
    historyDays: 90,
    regionType: 'Arid & Desert Spread',
    phcCount: 25,
  },
];

export const MEDICINES: Medicine[] = [
  {
    id: 'paracetamol',
    name: 'Paracetamol 500mg',
    unit: 'tablets',
    category: 'Analgesic / Antipyretic',
    coldChain: false,
    minDaysOfCover: 7,
    standardBoxQty: 500,
  },
  {
    id: 'ors',
    name: 'Oral Rehydration Salts (ORS)',
    unit: 'sachets',
    category: 'Essential Rehydration',
    coldChain: false,
    minDaysOfCover: 7,
    standardBoxQty: 200,
  },
  {
    id: 'amoxicillin',
    name: 'Amoxicillin 500mg',
    unit: 'capsules',
    category: 'Antibiotic',
    coldChain: false,
    minDaysOfCover: 10,
    standardBoxQty: 250,
  },
  {
    id: 'metformin',
    name: 'Metformin 500mg',
    unit: 'tablets',
    category: 'Antidiabetic',
    coldChain: false,
    minDaysOfCover: 14,
    standardBoxQty: 300,
  },
  {
    id: 'amlodipine',
    name: 'Amlodipine 5mg',
    unit: 'tablets',
    category: 'Antihypertensive',
    coldChain: false,
    minDaysOfCover: 14,
    standardBoxQty: 300,
  },
  {
    id: 'iron_folic',
    name: 'Iron & Folic Acid',
    unit: 'tablets',
    category: 'Maternal Health',
    coldChain: false,
    minDaysOfCover: 14,
    standardBoxQty: 500,
  },
  {
    id: 'zinc',
    name: 'Zinc Sulphate 20mg',
    unit: 'tablets',
    category: 'Pediatric Care',
    coldChain: false,
    minDaysOfCover: 10,
    standardBoxQty: 250,
  },
  {
    id: 'anti_snake_venom',
    name: 'Anti-Snake Venom (ASV)',
    unit: 'vials',
    category: 'Emergency Critical',
    coldChain: true,
    minDaysOfCover: 14,
    standardBoxQty: 20,
  },
  {
    id: 'oxytocin',
    name: 'Oxytocin Injection 5IU',
    unit: 'ampoules',
    category: 'Maternal Critical',
    coldChain: true,
    minDaysOfCover: 10,
    standardBoxQty: 50,
  },
  {
    id: 'cotrimoxazole',
    name: 'Cotrimoxazole 480mg',
    unit: 'tablets',
    category: 'Antibiotic',
    coldChain: false,
    minDaysOfCover: 10,
    standardBoxQty: 250,
  },
  {
    id: 'salbutamol',
    name: 'Salbutamol Inhaler 100mcg',
    unit: 'inhalers',
    category: 'Respiratory Care',
    coldChain: false,
    minDaysOfCover: 10,
    standardBoxQty: 30,
  },
  {
    id: 'insulin',
    name: 'Human Insulin 40IU/ml',
    unit: 'vials',
    category: 'Chronic Care',
    coldChain: true,
    minDaysOfCover: 14,
    standardBoxQty: 25,
  },
];

export const DISTRICTS_BY_STATE: Record<string, { name: string; lat: number; lng: number }[]> = {
  tn: [
    { name: 'Chennai', lat: 13.0827, lng: 80.2707 },
    { name: 'Coimbatore', lat: 11.0168, lng: 76.9558 },
    { name: 'Madurai', lat: 9.9252, lng: 78.1198 },
    { name: 'Tiruchirappalli', lat: 10.7905, lng: 78.7047 },
    { name: 'Salem', lat: 11.6643, lng: 78.146 },
    { name: 'Tirunelveli', lat: 8.7139, lng: 77.7567 },
  ],
  up: [
    { name: 'Lucknow', lat: 26.8467, lng: 80.9462 },
    { name: 'Varanasi', lat: 25.3176, lng: 82.9739 },
    { name: 'Gorakhpur', lat: 26.7606, lng: 83.3732 },
    { name: 'Kanpur Nagar', lat: 26.4499, lng: 80.3319 },
    { name: 'Agra', lat: 27.1767, lng: 78.0081 },
    { name: 'Prayagraj', lat: 25.4358, lng: 81.8463 },
  ],
  as: [
    { name: 'Kamrup Metropolitan', lat: 26.1445, lng: 91.7362 },
    { name: 'Dibrugarh', lat: 27.4728, lng: 94.912 },
    { name: 'Cachar (Silchar)', lat: 24.8333, lng: 92.7789 },
    { name: 'Jorhat', lat: 26.7509, lng: 94.2037 },
    { name: 'Nagaon', lat: 26.346, lng: 92.684 },
    { name: 'Barpeta', lat: 26.3228, lng: 91.0048 },
  ],
  rj: [
    { name: 'Jaipur', lat: 26.9124, lng: 75.7873 },
    { name: 'Jodhpur', lat: 26.2389, lng: 73.0243 },
    { name: 'Udaipur', lat: 24.5854, lng: 73.7125 },
    { name: 'Kota', lat: 25.2138, lng: 75.8648 },
    { name: 'Barmer', lat: 25.7532, lng: 71.4181 },
    { name: 'Bikaner', lat: 28.0229, lng: 73.3119 },
  ],
};
